config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }  
  resources :subscribes
  get 'welcome/index'

  root 'welcome#index'

  post 'welcome/invite', to: "welcome#invite", as: :invite_users

  get ":code", to: "welcome#refer", as: :refer_user

end

app/models/identity.rb
class Identity < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    identity = find_by(provider: auth.provider, uid: auth.uid)
    identity = create(uid: auth.uid, provider: auth.provider) if identity.nil?
    identity
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  before_create :assign_token
  has_many :referrers, class_name: "User", foreign_key: :referred_by_id


  def self.find_for_oauth(auth, signed_in_resource = nil)

    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?

      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      if user.nil?
        user = User.new(
          first_name: auth.extra.raw_info.name.split(" ").first,
          last_name: auth.extra.raw_info.name.split(" ").last,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token.first(8)
        )
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def full_name
    [first_name, last_name].compact.join(" ")
  end

  private

  def assign_token
  	random_code = self.first_name.try(:downcase) || self.email.try(:split, "@").try(:first).try(:gsub, ".", "")
    i = 1
  	while(!User.where(tracking_code: random_code).blank?)
      if(i > 1)
        random_code = random_code[0...(random_code.length - 1)] + i.to_s
      else
        random_code = random_code + i.to_s
      end
      i = i + 1
  	end
    self.tracking_code = random_code
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:facebook, :twitter].each do |provider|
    provides_callback_for provider
  end


end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController

	def create
		generated_password = Devise.friendly_token.first(8)
		debugger
		user = User.create!(user_params.merge({password: generated_password, sign_up_ip: request.ip}).merge(eval(cookies[:referrer_info])))

		Registration.welcome(user, generated_password).deliver
		sign_in(:user, user)

		redirect_to :root, notice: "Thanks for your subscription"
	end

	private

	def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end

end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController

	def create
		generated_password = Devise.friendly_token.first(8)
		@user = User.new(user_params.merge({password: generated_password, sign_up_ip: request.ip}).merge(eval(cookies[:referrer_info] || "{}")))
		if(@user.save)
			RegistrationMailer.welcome(@user, generated_password).deliver
			sign_in(:user, @user)
			redirect_to :root, notice: "Thanks for your subscription"
		else
			redirect_to :root, notice: @user.errors.full_messages.join(", ")
		end
	end

	private

	def user_params
    params.require(:post).permit(:email, :first_name, :last_name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		generated_password = Devise.friendly_token.first(8)
		user = User.create!(user_params.merge({password: generated_password, sign_up_ip: request.ip}).merge(eval(cookies[:referrer_info])))

		Registration.welcome(user, generated_password).deliver
		sign_in(:user, user)

		redirect_to :root, notice: "Thanks for your subscription"
	end

	private

	def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@user = User.new
  end

  def refer
  	cookies[:referrer_info] = {
		  value: { sign_up_source: request.referrer, referred_by_id: User.where(tracking_code: params[:code]).first.try(:id) }, 
		  expires: 1.year.from_now
  	}
  	redirect_to :root
  end

  def invite
    params[:emails].split(",").each do |email|
      email.strip!
      if email =~ /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i
        InviteMailer.invite(email, current_user).deliver!
      end
    end
    redirect_to :back, flash: {success: "Successfully invited users"}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PreLaunch" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %> 

  </head>
  <body class="body-with-bg">

    <div class="navbar navbar-default navbar-static-top zasny-navbar">
      <div class="container">
        <div class="col-md-12">
          
          <a href="/" class="navbar-brand">
            <%= image_tag "logo.png", class: "logo-image" %>
          </a>
          
          
            <ul class="nav navbar-nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
            </ul>
          
        </div>
      </div>
    </div>

    <%#= bootstrap_flash %>

    <div class="container">

      <div class="row">
        
        
        <%= yield %>
        
      </div><!--/row-->
    </div> <!-- /container -->
    <div class="clearfix"></div>
    <div class="footer">
      <div class="container">
        <div class="row footer-row">
          <%= render partial: "shared/footer" %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_footer.html.haml
.footer-nav-container
  %ul{class: "footer-nav"}
    %li
      = link_to "Home", "#"
    %li
      = link_to "About", "#"
    %li{class: "active"}
      = link_to "How it works", "#"
    %li
      = link_to "The shoes", "#"
    %li
      = link_to "The Expert", "#"
    %li
      = link_to "Shipping", "#"
    %li
      = link_to "Terms", "#"
    %li
      = link_to "Contact", "#"

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/_landing_page.html.haml
.welcome-form.home_form_wrap
  .col-md-6.welcome-message-block
    %h1 The world's premier shoe society!!
    .message An exclusive shoe collection of irresistible styles at insider prices, handpicked by our fashion experts specially for you.
    .membership Membership by invitation only
  .col-md-6.subscribe-form

    = form_for @user, url: subscribes_path, as: :post, html: {class: "register-form"} do |f|
      %h3{class: "col-md-9 form-title"} Request an invite
      .col-md-9.col-xs-12.home_form
        = f.text_field :email, placeholder: "Email address", class: "form-control input-lg email"
      .col-md-3.col-xs-12.home_button
        = f.submit "Submit", class: "btn btn-default btn-block btn-lg submit"

    .social-logins
      %a{href: user_omniauth_authorize_path(provider: "facebook"), class: "fb f_left"}
        .content
          %i{class: "fa fa-facebook-square"}
          %span Signup with facebook
      %a{href: user_omniauth_authorize_path(provider: "twitter"), class: "twitter f_right"}
        .content
          %i{class: "fa fa-twitter"}
          %span Signup with twitter
  .clearfix

app/views/welcome/_user_stats.html.haml
.user-stats
  .col-md-12.p_none
    %h1{class: "message"} The show sale begins in 75 days
  .col-md-6.left_section
    .col-md-12.priority-access
      %h3 Want priority access?
      %p Argentina is a megadiverse country hosting one of the greatest ecosystem varieties in the world: 15 continental zones, 3 oceanic zones, and the Antarctic region are all represented in its territory.

    .col-md-7
      %input{type: "text", value: refer_user_url(code: current_user.tracking_code), class: "form-control tracking-url"}
    .col-md-5.social-share
      %span share
      %a{href: "#", class: "share-in-fb"}
        %i{class: "fa fa-facebook"}
      %a{href: "#", class: "share-in-twitter"}
        %i{class: "fa fa-twitter"}

    .col-md-12.invite-via-mail
      = form_tag invite_users_path do 
        %input{type: "text", name: "emails", class: "form-control email-csv", placeholder: "Enter your friend's email seperated with comma"}
        %input{type: "submit", class: "btn btn-default btn-lg", value: "Submit"}

  .col-md-6.right_section
    %h3 You have earned Rs. 500 as credit  
    .progress
      .progress-bar.progress-bar-info{role: "progressbar", "aria-valuenow" => "20", "aria-valuemin" => "0", "aria-valuemax" => "100", style: "width: #{(((current_user.referrers.count * 100)/50) + 20)}%"}
        %span{class: "sr-only"} 20% Complete
    .bar-levels
      .col-md-4
        %i{class: "fa fa-caret-up"}
        .msg PRIORITY
      .col-md-4
        %i{class: "fa fa-caret-up"}
        .msg VIP
      .col-md-4
        %i{class: "fa fa-caret-up"}
        .msg PREMIUM
      .clearfix
    .access-level
      %h4 Access level
      %p Major wind currents include the cool Pampero Winds blowing on the flat plains of Patagonia and the Pampas. This invertor is a high effecieny inverter which actually protects your machine as it gives an audible signal in times of short cirtuiting and power overload
      %p It is most common in late autumn and winter along the central coast and in the Río de la Plata estuary. And the Antarctic region are all represented in its territory.
  .clearfix      

app/views/welcome/index.html.haml
- if user_signed_in?
  = render partial: "user_stats"
- else
  = render partial: "landing_page"

app/views/welcome/refer.html.erb
refer.html.erb